source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.8'
gem 'hashid-rails' #hash ids

gem 'default_value_for'

# use bootstrap
gem 'bootstrap-sass'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

gem 'qiniu', :git => 'https://github.com/jerecui/ruby-sdk'
gem 'carrierwave-qiniu'
gem 'rmagick'
gem 'file_validators'

# cors
gem 'rack-cors', :require => 'rack/cors'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'slim-rails'
gem 'will_paginate'
gem 'will_paginate-bootstrap'

gem 'devise'
gem 'pundit'
gem 'rolify'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem 'factory_girl_rails'

# Use mina for deployment
gem 'mina'
gem 'mina-unicorn', require: false
gem 'mina-nginx', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'

  gem 'rspec-rails'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
end

group :production do
  # Use Unicorn as the app server
  gem 'unicorn'

  # gem 'mysql2', require: false
  gem 'pg'
end
